[JIRA SONIC-13493] DELL: cherry picks changes from ARLO+
* 8e9c0f4 DELL: cherry picks mmu changes from dell_sonic_2.x_share to arlo+

* 9cffd45 DELL: cherry picks changes from dell_sonic_2.x_share to arlo+

* 4cacd31 DELL: cherry picks changes from dell_sonic to arlo+

In turns, it squashed the following commits from dell_sonic

commit a164262ca0db3cd385a3ff6ab189c2a41cbf6d70
Author: Sudharsan Dhamal Gopalratnam <sudharsan.gopalarath@dell.com>
Date:   Tue Nov 12 13:42:05 2019 -0800

    Removing dell specific mmu change and moving to broadcom defaults

commit 2e1cc9979cd019724e8176e1b3a0e64e0f6a0855
Author: Howard Persh <Howard_Persh@dell.com>
Date:   Wed Oct 30 17:52:43 2019 -0700

    [Dell, Dell EMC platforms] Fixes vulnerability to I2C renumbering

    The numbering of I2C busses directly attached to the CPU is done by the kernel, and cannot be known in advance.  Therefore, such I2C busses must be discovered at runtime, by bus name.

    This is corrected for all Dell and Dell EMC platforms: S3000/3048, S5232F, S5248F, S6000, S6100, Z9100, Z9264F and Z9332F.

    Signed-off-by: Howard Persh <Howard_Persh@dell.com>

commit 54a407e738efd2400f3ef7412d24f600b6dc2e2e
Author: Howard Persh <Howard_Persh@dell.com>
Date:   Wed Oct 23 13:16:22 2019 -0700

    Fixes system EEPROM failure for Dell S52xxF

    Do not assume that system EEPROM is on I2C bus 0 -- kernel can number I2C controllers directly attached to the CPU in any order.  Rather, search for the appropriate bus by name, and look up corresponding bus number.

    Signed-off-by: Howard Persh <Howard_Persh@dell.com>

commit de5663120c82d3caccb006a2e8f91954c7d46335
Author: Srideep Devireddy <srideep_devireddy@dell.com>
Date:   Fri Nov 8 20:56:05 2019 -0800

    Z9332 media support for DR4

commit b545d0cf6af993df9de95fa019f594502f005157
Author: Sudharsan Gopalarathinam <sudharsan_gopalarath@dell.com>
Date:   Wed Nov 6 15:58:08 2019 -0800

    Fixing build issue

commit 5d096ccb388623477fb67404f33c820dedbb2d09
Author: Sudharsan Gopalarathinam <sudharsan_gopalarath@dell.com>
Date:   Mon Nov 4 16:39:35 2019 -0800

    Added FEC settings for z9332f for 100G ports

commit 9e85cbccbf85072b5c1d5019e2b6c60db89784bf
Author: Sudharsan Gopalarathinam <sudharsan_gopalarath@dell.com>
Date:   Thu Oct 31 21:14:21 2019 -0700

    Modified media type for 100G top row ports

Change-Id: I07b33a6b2d43490d3383d0f90d7902f3f0960b12

diff --git a/platform/broadcom/sonic-platform-modules-s6000/debian/platform-modules-s6000.init b/platform/broadcom/sonic-platform-modules-s6000/debian/platform-modules-s6000.init
--- a/platform/broadcom/sonic-platform-modules-s6000/debian/platform-modules-s6000.init
+++ b/platform/broadcom/sonic-platform-modules-s6000/debian/platform-modules-s6000.init
@@ -11,12 +11,25 @@
 # Short-Description: Setup S6000 board.
 ### END INIT INFO
 
+init_devnum() {
+    found=0
+    for devnum in 0 1; do
+        devname=`cat /sys/bus/i2c/devices/i2c-${devnum}/name`
+        if [[ $devname == 'SMBus iSMT adapter at ff781000' ]]; then
+            found=1
+            break
+        fi
+    done
+
+    [ $found -eq 0 ] && echo "cannot find iSMT" && exit 1
+}
+
 add_i2c_devices() {
 
-    echo 24c02 0x50 > /sys/class/i2c-adapter/i2c-1/new_device
-    echo 24c02 0x51 > /sys/class/i2c-adapter/i2c-1/new_device
-    echo dni_dps460 0x58 > /sys/class/i2c-adapter/i2c-1/new_device
-    echo dni_dps460 0x59 > /sys/class/i2c-adapter/i2c-1/new_device
+    echo 24c02 0x50 > /sys/class/i2c-adapter/i2c-${devnum}/new_device
+    echo 24c02 0x51 > /sys/class/i2c-adapter/i2c-${devnum}/new_device
+    echo dni_dps460 0x58 > /sys/class/i2c-adapter/i2c-${devnum}/new_device
+    echo dni_dps460 0x59 > /sys/class/i2c-adapter/i2c-${devnum}/new_device
     echo jc42 0x18 > /sys/class/i2c-adapter/i2c-10/new_device
     echo emc1403 0x4d > /sys/class/i2c-adapter/i2c-10/new_device
     echo spd 0x50 > /sys/class/i2c-adapter/i2c-10/new_device
@@ -37,10 +50,10 @@ add_i2c_devices() {
 }
 
 remove_i2c_devices() {
-    echo 0x50 > /sys/class/i2c-adapter/i2c-1/delete_device
-    echo 0x51 > /sys/class/i2c-adapter/i2c-1/delete_device
-    echo 0x58 > /sys/class/i2c-adapter/i2c-1/delete_device
-    echo 0x59 > /sys/class/i2c-adapter/i2c-1/delete_device
+    echo 0x50 > /sys/class/i2c-adapter/i2c-${devnum}/delete_device
+    echo 0x51 > /sys/class/i2c-adapter/i2c-${devnum}/delete_device
+    echo 0x58 > /sys/class/i2c-adapter/i2c-${devnum}/delete_device
+    echo 0x59 > /sys/class/i2c-adapter/i2c-${devnum}/delete_device
     echo 0x18 > /sys/class/i2c-adapter/i2c-10/delete_device
     echo 0x4d > /sys/class/i2c-adapter/i2c-10/delete_device
     echo 0x50 > /sys/class/i2c-adapter/i2c-10/delete_device
@@ -59,6 +72,8 @@ remove_i2c_devices() {
         echo 0x50 > /sys/class/i2c-adapter/i2c-$((20+i))/delete_device
     done
 }
+
+init_devnum
 
 case "$1" in
 start)
