[JIRA SONIC-8408] PMON enhancements: Store EEPROM info in databse while launching PMON
Change-Id: I157c6453cf8b1c299bcb3f975b61c722c36a7571

diff --git a/files/build_templates/docker_image_ctl.j2 b/files/build_templates/docker_image_ctl.j2
--- a/files/build_templates/docker_image_ctl.j2
+++ b/files/build_templates/docker_image_ctl.j2
@@ -92,6 +92,14 @@ function preStartAction()
     do
       sed -i "s|S'[0-9]*'|S'0'|g" $file
     done
+{%- elif docker_container_name == "pmon" %}
+    # Initialize the eeprom info in databse
+    sudo decode-syseeprom --init
+	if [ $? -ne 0 ]; then
+		echo "EEPROM info initialization into database failed"
+	else
+		echo "EEPROM info initialized in database successfully"
+	fi
 {%- else %}
     : # nothing
 {%- endif %}
